# Generated by Django 5.2 on 2025-05-01 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('image', models.ImageField(blank=True, default='def.png', upload_to='images/')),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Cristian', 'Cristian'), ('Buddho', 'Buddho')], max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('third', 'third')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('roll', models.IntegerField()),
                ('city', models.CharField(max_length=10)),
                ('is_Bangladeshi', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.PositiveBigIntegerField()),
                ('result', models.ManyToManyField(to='student_management_app.result')),
                ('Subject', models.ManyToManyField(to='student_management_app.subject')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='Subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.subject'),
        ),
    ]
