# Generated by Django 5.2 on 2025-05-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_hobby_rename_subject_result_subject_student_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='logo.png', upload_to='images/'),
        ),
    ]
