# Generated by Django 5.2 on 2025-05-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_remove_student_created_at_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.TextField(),
        ),
    ]
